/** Autogenerated Main.cpp. */

// =============================| Include only the DSP files  |=============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =======================| Now we can add the rest of the codebase |=======================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ===================================| Project Factory |===================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------
		
		registerPolyNode<project::Dynamics<1>, wrap::illegal_poly<project::Dynamics<1>>>();
		registerDataNode<project::Gate_networkdata>();
		registerDataNode<project::MakeupBoost_networkdata>();
		registerDataNode<project::Peak_networkdata>();
		registerDataNode<project::PeakOut_networkdata>();
		registerDataNode<project::PostComp_networkdata>();
		registerDataNode<project::PreComp_networkdata>();
	}
};

#if HISE_INCLUDE_RT_NEURAL

struct NeuralFactory: public hise::NeuralNetwork::Factory
{
	NeuralFactory()
	{
	}
	void* cloneModel(void* model) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			return m->clone();
		}
		return nullptr;
	}
	void destroyModel(void* model) const
	{
		delete static_cast<hise::NeuralNetwork::ModelBase*>(model);
	}
	void resetModel(void* model) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			m->reset();
		}
	}
	void processModel(void* model, const float* input, float* output) const
	{
		if(auto m = static_cast<hise::NeuralNetwork::ModelBase*>(model))
		{
			m->process(input, output);
		}
	}
};
#endif
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if HISE_INCLUDE_RT_NEURAL
void scriptnode::DspNetwork::registerStaticNeuralNetworks(hise::NeuralNetwork::Factory* f)
{
}
#endif

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


